### ISSUE TITLE
Some Questions...

### ISSUE THREAD

**Issue by FahimFuad** [inanevin/LinaEngine#51]
I was seeing this repo and found out a very  interesting thing about the window... The title bar of the window is totally changed. It doesn't look like the normal, typical window title bar in WindowsOS. I have seen that this project uses GLFW. Can I see the code which does the styling ⬇️ 
![image](https://user-images.githubusercontent.com/69952230/104094353-ac1e6580-52ba-11eb-9f29-21ae13dc339e.png)
Any help regarding this styling and how it is done is appreciated. You can also tell me the file name in which this style-ing is done.
Thanks In Advance! 😄

**Comment by inanevin** [comment]
> I was seeing this repo and found out a very interesting thing about the window... The title bar of the window is totally changed. It doesn't look like the normal, typical window title bar in WindowsOS. I have seen that this project uses GLFW. Can I see the code which does the styling ⬇️
> ![image](https://user-images.githubusercontent.com/69952230/104094353-ac1e6580-52ba-11eb-9f29-21ae13dc339e.png)
> Any help regarding this styling and how it is done is appreciated. You can also tell me the file name in which this style-ing is done.
> Thanks In Advance! 😄

Hey, [here ](https://github.com/inanevin/LinaEngine/blob/master/LinaGraphics/src/PackageManager/OpenGL/GLWindow.cpp)is the Window class preparing & handling the decoration of the GLFW window so that we won't have the default Windows titlebar and buttons.

And [here](https://github.com/inanevin/LinaEngine/blob/master/LinaEditor/src/Panels/HeaderPanel.cpp) is the editor implementation responsible for the custom window rendering.
