### ISSUE TITLE
Add game-engine topics

### ISSUE THREAD

**Issue by C-BJ** [inanevin/LinaEngine#56]
This will attract more people to learn about the project

**Comment by inanevin** [comment]
Yes the current docs/info is pretty out-dated. The engine has come far too since the current available info and I plan to start topics, proper documentation after I complete the development branch :). Working on a Vulkan renderer and a new GUI system based on LinaVG at the moment.

**Comment by C-BJ** [comment]
> Yes the current docs/info is pretty out-dated. The engine has come far too since the current available info and I plan to start topics, proper documentation after I complete some more work on the development branch :). Working on a Vulkan renderer and a new GUI system based on LinaVG at the moment.

Sorry, I mean the GitHub topics of the project

btw, Does the project plan to use its own GUI system refactoring editor and Is it possible for this project to become a real game engine from a research project? I think people might be interested

**Comment by C-BJ** [comment]
For the suggestion of game engine, I think it is a good choice to use wgpu as the low-level graphics API (instead of OpenGL, DX, metal, Vulkan). In this way, it is not necessary to maintain multiple low-level graphics APIs. Maybe Lina can use Google's wgpu implementation named dawn

It's just my own idea

**Comment by inanevin** [comment]
> Great work, but I mean the GitHub topics of the project:

Oh yeah right, added ty! :).

> btw, Does the project plan to use its own GUI system refactoring editor, the benefits of this have been verified on Godot.

Yes so far I've been using Dear ImGui for the editor & planned in-game GUI system but I've developed [LinaVG](https://github.com/inanevin/LinaVG) so that I can implement 100% my own framework for both the editor and in-game GUI.

> Is it possible for this project to become a real game engine from a research project?....

Yes that's what I've been focused on for the last year. Until last year or so the idea was to explore game engine architecture possibilities and provide a proof-of concept for my thesis. This was the core plan for the Lina between 2019-2021. But since last year I've been refactoring, developing & modifying the architecture & structure so that it can be a fully-fledged game engine, specifically aimed for custom works & indie games. Current `master` branch still reflects the earlier plan, meanwhile `development` branch is a targeted in-progress stuff for a real game engine.


> I also have a question, the game engine using MIT + Apache2.0 license is better

I plan for MIT all over, previously Apache 2.0 was used when this was aimed for research project only. Some files in the master branch still has Apache 2.0 headers, which are removed in the development branch. Commenting out was a simple copy-paste error, it's fixed, thanks for pointing it out :).


> Not all discussions are suitable for discord, For example, discussion of specific functions and ideas. I hope to open GitHub discussions

Yes that's the plan, proper github discussions, roadmap as projects etc.

> Thank you for reading carefully
> I don't know if you'll mind if I give you so many non-game-engine suggestions...

Not minding at all, I appreciate your suggestions & possible contributions, and your interest in Lina Engine makes me really happy! Thank you for all the ideas/discussion, keep em coming whenever you want to. I'm developing Lina on my own for the last 3-4 years, and it's really hard to focus on the bureaucracy of things (github, organization, repos, docs) when I'm focused on engine architecture, rendering, physics etc. along with my full-time job :)

Just to give you an idea of the roadmap, my plan is to ditch the old Deferred OpenGL PBR renderer, finish the current Forward Pass Vulkan renderer I'm working on, refactor the editor to use LinaVG instead of Dear ImGui. Then I feel like Lina will be on a stage where people can actually code for making the games. I mean you can do that still, but it's not as ready as a proper game-engine-framework. Once I reach that stage, hopefully this year, I plan to focus on all about documentation, better project tool-chain, discussions, roadmap etc. etc.

**Comment by inanevin** [comment]
> For the suggestion of game engine, I think it is a good choice to use wgpu as the low-level graphics API (instead of OpenGL, DX, metal, Vulkan). In this way, it is not necessary to maintain multiple low-level graphics APIs. Maybe Lina can use Google's wgpu implementation named dawn
> 
> It's just my own idea @inanevin

I want Lina to focus on cross-platform PC games, and don't particularly believe-in nor have the enough information about Web GPU tech, yet. Maybe for the future a wgpu renderer can be implemented, but for a while the renderer plans have been to carry Lina from OpenGL to Vulkan :).

**Comment by C-BJ** [comment]
> > For the suggestion of game engine, I think it is a good choice to use wgpu as the low-level graphics API (instead of OpenGL, DX, metal, Vulkan). In this way, it is not necessary to maintain multiple low-level graphics APIs. Maybe Lina can use Google's wgpu implementation named dawn
> > It's just my own idea @inanevin
> 
> I want Lina to focus on cross-platform PC games, and don't particularly believe-in nor have the enough information about Web GPU tech, yet. Maybe for the future a wgpu renderer can be implemented, but for a while the renderer plans have been to carry Lina from OpenGL to Vulkan :).

I mean, wgpu is actually the encapsulation of various underlying graphics APIs, not just for the web
@inanevin

**Comment by inanevin** [comment]
> > > For the suggestion of game engine, I think it is a good choice to use wgpu as the low-level graphics API (instead of OpenGL, DX, metal, Vulkan). In this way, it is not necessary to maintain multiple low-level graphics APIs. Maybe Lina can use Google's wgpu implementation named dawn
> > > It's just my own idea @inanevin
> > 
> > 
> > I want Lina to focus on cross-platform PC games, and don't particularly believe-in nor have the enough information about Web GPU tech, yet. Maybe for the future a wgpu renderer can be implemented, but for a while the renderer plans have been to carry Lina from OpenGL to Vulkan :).
> 
> I mean, wgpu is actually the encapsulation of various underlying graphics APIs, not just for the web @inanevin

Yes I am aware, however as said I haven't taken a detailed look at it yet and like to keep things simple with my own Backend/Renderer logic. This is also the reason why Lina doesn't use available API abstraction systems like bgfx or google filament.

**Comment by C-BJ** [comment]
> > Great work, but I mean the GitHub topics of the project:
> 
> Oh yeah right, added ty! :).
> 
> > btw, Does the project plan to use its own GUI system refactoring editor, the benefits of this have been verified on Godot.
> 
> Yes so far I've been using Dear ImGui for the editor & planned in-game GUI system but I've developed [LinaVG](https://github.com/inanevin/LinaVG) so that I can implement 100% my own framework for both the editor and in-game GUI.
> 
> > Is it possible for this project to become a real game engine from a research project?....
> 
> Yes that's what I've been focused on for the last year. Until last year or so the idea was to explore game engine architecture possibilities and provide a proof-of concept for my thesis. This was the core plan for the Lina between 2019-2021. But since last year I've been refactoring, developing & modifying the architecture & structure so that it can be a fully-fledged game engine, specifically aimed for custom works & indie games. Current branch still reflects the earlier plan, meanwhile branch is a targeted in-progress stuff for a real game engine.`master``development`
> 
> > I also have a question, the game engine using MIT + Apache2.0 license is better
> 
> I plan for MIT all over, previously Apache 2.0 was used when this was aimed for research project only. Some files in the master branch still has Apache 2.0 headers, which are removed in the development branch. Commenting out was a simple copy-paste error, it's fixed, thanks for pointing it out :).
> 
> > Not all discussions are suitable for discord, For example, discussion of specific functions and ideas. I hope to open GitHub discussions
> 
> Yes that's the plan, proper github discussions, roadmap as projects etc.
> 
> > Thank you for reading carefully
> > I don't know if you'll mind if I give you so many non-game-engine suggestions...
> 
> Not minding at all, I appreciate your suggestions & possible contributions, and your interest in Lina Engine makes me really happy! Thank you for all the ideas/discussion, keep em coming whenever you want to. I'm developing Lina on my own for the last 3-4 years, and it's really hard to focus on the bureaucracy of things (github, organization, repos, docs) when I'm focused on engine architecture, rendering, physics etc. along with my full-time job :)
> 
> Just to give you an idea of the roadmap, my plan is to ditch the old Deferred OpenGL PBR renderer, finish the current Forward Pass Vulkan renderer I'm working on, refactor the editor to use LinaVG instead of Dear ImGui. Then I feel like Lina will be on a stage where people can actually code for making the games. I mean you can do that still, but it's not as ready as a proper game-engine-framework. Once I reach that stage, hopefully this year, I plan to focus on all about documentation, better project tool-chain, discussions, roadmap etc. etc.

I think you have some misunderstanding
I mean, MIT + Apache 2.0 may be better than MIT
I hope to open the GitHub discussion function

**Comment by inanevin** [comment]
> I think you have some misunderstanding I mean, MIT + Apache 2.0 may be better than MIT I hope to open the GitHub discussion function @inanevin

Discussions opened now, we can talk about that further in the discussions, I have some concerns regarding licenses as there are a lot of 3rd party stuff involved as well. Closing the issue.
